export default [
 {
  files:['**/*.js','**/*.mjs'],
  ignores:['node_modules/**'],
  languageOptions:{ecmaVersion:'latest',sourceType:'module'},
  rules:{
   'constructor-super':'error',
   'for-direction':'error',
   'getter-return':'error',
   'no-async-promise-executor':'error',
   'no-class-assign':'error',
   'no-compare-neg-zero':'error',
   'no-cond-assign':'error',
   'no-constant-binary-expression':'error',
   'no-dupe-args':'error',
   'no-dupe-class-members':'error',
   'no-dupe-else-if':'error',
   'no-dupe-keys':'error',
   'no-func-assign':'error',
   'no-import-assign':'error',
   'no-loss-of-precision':'error',
   'no-new-native-nonconstructor':'error',
   'no-obj-calls':'error',
   'no-redeclare':'error',
   'no-self-assign':'error',
   'no-setter-return':'error',
   'no-sparse-arrays':'error',
   'no-unreachable':'error',
   'no-unreachable-loop':'error',
   'no-unsafe-finally':'error',
   'no-unsafe-negation':'error',
   'no-unexpected-multiline':'error',
   'require-yield':'error',
   'use-isnan':'error',
   'valid-typeof':'error'
  }
 }
];
